(() => {
  'use strict';

  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const lerp=(a,b,t)=>a+(b-a)*t;
  const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
  const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
  const scale=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
  const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
  const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
  const length=a=>Math.hypot(a[0],a[1],a[2]);
  const normalize=a=>{const n=length(a)||1;return [a[0]/n,a[1]/n,a[2]/n];};
  const identity=()=>[1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1];
  const multiply=(a,b)=>{const out=new Array(16).fill(0);for(let row=0;row<4;row++)for(let column=0;column<4;column++)for(let k=0;k<4;k++)out[column*4+row]+=a[k*4+row]*b[column*4+k];return out;};
  const perspective=(fov,aspect,near,far)=>{const f=1/Math.tan(fov/2),nf=1/(near-far);return [f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0];};
  const orthographic=(halfHeight,aspect,near,far)=>{const halfWidth=halfHeight*aspect,rl=1/(2*halfWidth),tb=1/(2*halfHeight),nf=1/(near-far);return [2*rl,0,0,0,0,2*tb,0,0,0,0,2*nf,0,0,0,(far+near)*nf,1];};
  const lookAt=(eye,target,up)=>{const forward=normalize(sub(target,eye)),right=normalize(cross(forward,up)),cameraUp=cross(right,forward);return {matrix:[right[0],cameraUp[0],-forward[0],0,right[1],cameraUp[1],-forward[1],0,right[2],cameraUp[2],-forward[2],0,-dot(right,eye),-dot(cameraUp,eye),dot(forward,eye),1],right,up:cameraUp,forward};};
  const project=(point,matrix,width,height)=>{const x=point[0],y=point[1],z=point[2],w=matrix[3]*x+matrix[7]*y+matrix[11]*z+matrix[15];if(w<=0)return null;const nx=(matrix[0]*x+matrix[4]*y+matrix[8]*z+matrix[12])/w,ny=(matrix[1]*x+matrix[5]*y+matrix[9]*z+matrix[13])/w;return {x:(nx*.5+.5)*width,y:(1-(ny*.5+.5))*height,depth:w};};
  const shader=(gl,type,source)=>{const value=gl.createShader(type);gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(value)||'Falha ao compilar shader.');return value;};
  const program=(gl,vertex,fragment)=>{const value=gl.createProgram();gl.attachShader(value,shader(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(value,shader(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(value);if(!gl.getProgramParameter(value,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(value)||'Falha ao ligar shader.');return value;};
  const flat=array=>new Float32Array(array.flat());

  const surfaceVertex=`attribute vec3 aPosition;attribute vec3 aNormal;uniform mat4 uMvp;varying vec3 vNormal;void main(){vNormal=aNormal;gl_Position=uMvp*vec4(aPosition,1.0);}`;
  const surfaceFragment=`precision mediump float;uniform vec4 uColor;uniform vec3 uKeyLight;uniform vec3 uFillLight;varying vec3 vNormal;void main(){vec3 n=normalize(vNormal);float key=max(dot(n,normalize(uKeyLight)),0.0);float fill=max(dot(n,normalize(uFillLight)),0.0);float sky=.5+.5*n.z;vec3 color=uColor.rgb*(.42+.34*key+.13*fill+.11*sky)+vec3(.006,.018,.038);gl_FragColor=vec4(color,uColor.a);}`;
  const lineVertex=`attribute vec3 aPosition;uniform mat4 uMvp;uniform float uSize;void main(){gl_Position=uMvp*vec4(aPosition,1.0);gl_PointSize=uSize;}`;
  const lineFragment=`precision mediump float;uniform vec4 uColor;uniform float uRound;void main(){if(uRound>0.5&&length(gl_PointCoord-vec2(.5))>.5)discard;gl_FragColor=uColor;}`;

  class HydroRender3D {
    constructor(canvas,callbacks={}) {
      this.canvas=canvas;this.callbacks=callbacks;this.gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});
      if(!this.gl)throw new Error('WebGL não está disponível neste navegador.');
      this.gl.enable(this.gl.DEPTH_TEST);this.gl.depthFunc(this.gl.LEQUAL);this.gl.enable(this.gl.BLEND);this.gl.blendFunc(this.gl.SRC_ALPHA,this.gl.ONE_MINUS_SRC_ALPHA);
      this.surfaceProgram=program(this.gl,surfaceVertex,surfaceFragment);this.lineProgram=program(this.gl,lineVertex,lineFragment);
      this.surface={};this.lines=[];this.visibleLineBuffers=[];this.debugLineBuffers=[];this.pointBuffer=null;this.gridBuffer=null;this.axisVectors=[];this.planeBuffer=null;this.planeNormal=null;this.pickPoints=[];this.bounds={min:[0,-1,0],max:[1,1,1],center:[.5,0,.5],radius:1};
      this.options={mode:'surfaceCurves',showGrid:false,showAxes:false,showKeel:true,showChine:true,showSheer:true,showStations:true,showWaterlines:true,showLongitudinals:false,showOffsets:false,showWaterplane:false,stationDensity:.25,waterlineDensity:.25,longitudinalDensity:.1,visualScale:'naval',projection:'perspective'};
      this.camera={target:[0,0,0],desiredTarget:[0,0,0],radius:8,desiredRadius:8,azimuth:-.72,desiredAzimuth:-.72,elevation:.48,desiredElevation:.48};this.hover=null;this.drag=null;this.frame=0;this.framePending=false;this.lastFrameTime=0;this.rawData=null;this.rawPlanePositions=[];this.rawBounds=this.bounds;this.resizeObserver=null;this.performance={windowStarted:performance.now(),frames:0,windowFrames:0,renderMs:0,windowRenderMs:0,fps:0,averageRenderMs:0,lastRenderMs:0,drawCalls:0,idle:true};
      this.debug={phase:'ready',surfaceVertices:0,surfaceTriangles:0,lastGlError:0,performance:this.performance};window.__hydroViewerDebug=this.debug;
      this.createOverlay();this.bind();this.resize();this.requestRender();
    }
    createOverlay(){let viewport=this.canvas.closest('.viewer-canvas-wrap');if(!viewport){viewport=document.createElement('div');viewport.className='viewer-canvas-wrap';this.canvas.parentNode?.insertBefore(viewport,this.canvas);viewport.appendChild(this.canvas);}this.viewport=viewport;this.overlay=viewport.querySelector('.orientation-gizmo')||document.createElement('canvas');this.overlay.className='orientation-gizmo';this.overlay.setAttribute('aria-label','Triedro de orientação XYZ');this.overlay.setAttribute('aria-hidden','true');if(!this.overlay.parentElement)viewport.appendChild(this.overlay);this.overlayContext=this.overlay.getContext('2d');this.errorLabel=viewport.querySelector('.viewer-error-overlay')||document.createElement('div');this.errorLabel.className='viewer-error-overlay';this.errorLabel.setAttribute('role','status');this.errorLabel.setAttribute('aria-live','polite');if(!this.errorLabel.parentElement)viewport.appendChild(this.errorLabel);}
    createBuffer(values,usage){const buffer=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,buffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,values,usage||this.gl.STATIC_DRAW);return {buffer,count:values.length/3};}
    releaseBuffer(value){if(value?.buffer)this.gl.deleteBuffer(value.buffer);}
    clearData(){this.releaseBuffer(this.surface.position);this.releaseBuffer(this.surface.normal);if(this.surface.index)this.gl.deleteBuffer(this.surface.index);this.lines.forEach(line=>this.releaseBuffer(line.buffer));this.axisVectors.forEach(axis=>{this.releaseBuffer(axis.shaft);this.releaseBuffer(axis.head);});this.releaseBuffer(this.pointBuffer);this.releaseBuffer(this.gridBuffer);this.releaseBuffer(this.planeBuffer);this.releaseBuffer(this.planeNormal);this.surface={};this.lines=[];this.visibleLineBuffers=[];this.debugLineBuffers=[];this.axisVectors=[];this.pointBuffer=null;this.gridBuffer=null;this.planeBuffer=null;this.planeNormal=null;}
    createSurface(data){const positions=new Float32Array(data.indices.length*3),normals=new Float32Array(data.indices.length*3),cornerNormals=data.cornerNormals?.length===data.indices.length*3?data.cornerNormals:null;data.indices.forEach((sourceIndex,targetIndex)=>{const from=sourceIndex*3,to=targetIndex*3;positions[to]=data.positions[from];positions[to+1]=data.positions[from+1];positions[to+2]=data.positions[from+2];normals[to]=cornerNormals?cornerNormals[to]:data.normals[from];normals[to+1]=cornerNormals?cornerNormals[to+1]:data.normals[from+1];normals[to+2]=cornerNormals?cornerNormals[to+2]:data.normals[from+2];});this.surface={position:this.createBuffer(positions),normal:this.createBuffer(normals),count:data.indices.length,index:null};}
    createAxisVectors(bounds){const origin=[bounds.min[0],0,bounds.min[2]],axisLength=Math.max(bounds.max[0]-bounds.min[0],bounds.max[1]-bounds.min[1],bounds.max[2]-bounds.min[2],1)*.085,make=(direction,color,name)=>{const rawTip=add(origin,scale(direction,axisLength)),start=this.transformPositions(origin),tip=this.transformPositions(rawTip),unit=normalize(sub(tip,start)),headLength=Math.max(length(sub(tip,start))*.16,.035),headWidth=headLength*.3,base=add(tip,scale(unit,-headLength)),reference=Math.abs(unit[2])>.82?[0,1,0]:[0,0,1],side=normalize(cross(unit,reference)),up=normalize(cross(side,unit)),corners=[add(add(base,scale(side,headWidth)),scale(up,headWidth)),add(add(base,scale(side,-headWidth)),scale(up,headWidth)),add(add(base,scale(side,-headWidth)),scale(up,-headWidth)),add(add(base,scale(side,headWidth)),scale(up,-headWidth))],head=[];for(let i=0;i<4;i++)head.push(...tip,...corners[i],...corners[(i+1)%4]);return {name,color,shaft:this.createBuffer(new Float32Array([...start,...base])),head:this.createBuffer(new Float32Array(head))};};this.axisVectors=[make([1,0,0],[1,.361,.478,1],'X'),make([0,1,0],[.333,.780,1,1],'Y'),make([0,0,1],[.271,.890,.639,1],'Z')];}
    visualScale(){return {real:[1,1,1],naval:[1,1.4,1.65],inspection:[1,1.75,2]}[this.options.visualScale]||[1,1.4,1.65];}
    transformPositions(values){const [sx,sy,sz]=this.visualScale(),center=this.rawBounds?.center||[0,0,0],out=[];for(let i=0;i<values.length;i+=3)out.push(center[0]+(values[i]-center[0])*sx,values[i+1]*sy,center[2]+(values[i+2]-center[2])*sz);return out;}
    transformNormals(values){const [,sy,sz]=this.visualScale(),out=[];for(let i=0;i<values.length;i+=3){const n=normalize([values[i],values[i+1]/sy,values[i+2]/sz]);out.push(...n);}return out;}
    scaledBounds(bounds){const min=this.transformPositions(bounds.min),max=this.transformPositions(bounds.max),center=this.transformPositions(bounds.center),extent=[max[0]-min[0],max[1]-min[1],max[2]-min[2]];return {min,max,center,radius:Math.max(...extent,1)*.55};}
    rebuildData(){if(!this.rawData)return;const data=this.rawData;this.clearData();this.rawBounds=data.bounds;const surface={positions:this.transformPositions(data.surface.positions),normals:this.transformNormals(data.surface.normals),cornerNormals:data.surface.cornerNormals?.length===data.surface.indices.length*3?this.transformNormals(data.surface.cornerNormals):null,indices:data.surface.indices};this.createSurface(surface);this.lines=(data.lines||[]).map(line=>({...line,buffer:this.createBuffer(new Float32Array(this.transformPositions(line.positions)))}));this.pointBuffer=data.originalPoints?.length?this.createBuffer(new Float32Array(this.transformPositions(data.originalPoints))):null;this.gridBuffer=data.grid?.length?this.createBuffer(new Float32Array(this.transformPositions(data.grid))):null;this.createAxisVectors(data.bounds);this.pickPoints=(data.pickPoints||[]).map(item=>({...item,physicalPosition:[...item.position],position:this.transformPositions(item.position)}));this.bounds=this.scaledBounds(data.bounds);this.performance.vertices=surface.positions.length/3;this.performance.triangles=surface.indices.length/3;this.debug={phase:'data',surfaceVertices:this.performance.vertices,surfaceTriangles:this.performance.triangles,lineSets:this.lines.length,pickPoints:this.pickPoints.length,lastGlError:0,performance:this.performance};this.refreshVisibleLines();window.__hydroViewerDebug=this.debug;this.fit();if(this.rawPlanePositions.length)this.updateWaterplaneBuffer();}
    setData(data){this.rawData=data;this.rawBounds=data.bounds;this.rebuildData();this.performance.frames=0;this.requestRender();}
    setOptions(options){const previousScale=this.options.visualScale;this.options={...this.options,...options};if(previousScale!==this.options.visualScale&&this.rawData)this.rebuildData();else this.refreshVisibleLines();this.handleResize();this.requestRender();}
    updateWaterplaneBuffer(){this.releaseBuffer(this.planeBuffer);this.releaseBuffer(this.planeNormal);const positions=this.rawPlanePositions;this.planeBuffer=positions?.length?this.createBuffer(new Float32Array(this.transformPositions(positions))):null;this.planeNormal=this.planeBuffer?this.createBuffer(new Float32Array(Array.from({length:this.planeBuffer.count},()=>[0,0,1]).flat())):null;}
    setWaterplane(positions){this.rawPlanePositions=positions||[];this.updateWaterplaneBuffer();this.requestRender();}
    fit(){const b=this.bounds;this.camera.target=[...b.center];this.camera.desiredTarget=[...b.center];this.camera.radius=b.radius*2.35;this.camera.desiredRadius=this.camera.radius;this.camera.azimuth=-.72;this.camera.desiredAzimuth=-.72;this.camera.elevation=.48;this.camera.desiredElevation=.48;this.requestRender();}
    setView(view){const b=this.bounds,r=Math.max(b.radius*2.2,.2),poses={perspective:[-.68,.42],isometric:[-.78,.56],top:[-.74,1.52],port:[-Math.PI/2,.04],starboard:[Math.PI/2,.04],bow:[0,.05],stern:[Math.PI,.05],front:[0,.05],reset:[-.68,.42]};const pose=poses[view]||poses.perspective;this.camera.desiredTarget=[...b.center];this.camera.desiredAzimuth=pose[0];this.camera.desiredElevation=pose[1];this.camera.desiredRadius=r;this.requestRender();}
    bind(){
      this.canvas.addEventListener('contextmenu',event=>event.preventDefault());
      this.canvas.addEventListener('pointerdown',event=>{this.canvas.setPointerCapture(event.pointerId);this.drag={x:event.clientX,y:event.clientY,button:event.button,pan:event.button===2||event.shiftKey,moved:false};});
      this.canvas.addEventListener('pointermove',event=>{if(!this.drag){this.updateHover(event);return;}const dx=event.clientX-this.drag.x,dy=event.clientY-this.drag.y;if(Math.abs(dx)+Math.abs(dy)>2)this.drag.moved=true;if(this.drag.pan)this.pan(dx,dy);else{this.camera.desiredAzimuth-=dx*.012;this.camera.desiredElevation=clamp(this.camera.desiredElevation+dy*.012,-1.52,1.52);}this.drag.x=event.clientX;this.drag.y=event.clientY;this.requestRender();});
      this.canvas.addEventListener('pointerup',event=>{const wasDrag=this.drag;this.drag=null;if(wasDrag&&!wasDrag.moved)this.pick(event);this.requestRender();});
      this.canvas.addEventListener('pointercancel',()=>{this.drag=null;this.requestRender();});
      this.canvas.addEventListener('pointerleave',()=>{if(!this.drag){this.hover=null;this.callbacks.onHover?.(null);}});
      this.canvas.addEventListener('wheel',event=>{event.preventDefault();this.camera.desiredRadius=clamp(this.camera.desiredRadius*Math.exp(event.deltaY*.001),this.bounds.radius*.15,this.bounds.radius*18);this.requestRender();},{passive:false});
      this.canvas.addEventListener('dblclick',()=>this.fit());this.handleWindowResize=()=>this.handleResize();window.addEventListener('resize',this.handleWindowResize);if(typeof ResizeObserver!=='undefined'){this.resizeObserver=new ResizeObserver(()=>this.handleResize());this.resizeObserver.observe(this.canvas);}
    }
    pan(dx,dy){const basis=this.cameraBasis(this.camera.desiredAzimuth,this.camera.desiredElevation),factor=this.camera.desiredRadius/Math.max(this.canvas.clientHeight,1)*1.5,delta=add(scale(basis.right,-dx*factor),scale(basis.up,dy*factor));this.camera.desiredTarget=add(this.camera.desiredTarget,delta);}
    cameraBasis(azimuth,elevation){const offset=[Math.cos(elevation)*Math.cos(azimuth),Math.cos(elevation)*Math.sin(azimuth),Math.sin(elevation)],eye=add(this.camera.target,scale(offset,this.camera.radius)),look=lookAt(eye,this.camera.target,[0,0,1]);return {...look,eye};}
    handleResize(){if(this.resize())this.requestRender();}
    resize(){const cssWidth=Math.round(this.canvas.clientWidth),cssHeight=Math.round(this.canvas.clientHeight);if(!cssWidth||!cssHeight)return false;const ratio=Math.min(window.devicePixelRatio||1,1.5),width=Math.max(1,Math.round(cssWidth*ratio)),height=Math.max(1,Math.round(cssHeight*ratio)),overlayCssWidth=Math.max(1,Math.round(this.overlay.clientWidth||135)),overlayCssHeight=Math.max(1,Math.round(this.overlay.clientHeight||112)),overlayWidth=Math.round(overlayCssWidth*ratio),overlayHeight=Math.round(overlayCssHeight*ratio),changed=this.canvas.width!==width||this.canvas.height!==height||this.overlay.width!==overlayWidth||this.overlay.height!==overlayHeight;if(this.canvas.width!==width||this.canvas.height!==height){this.canvas.width=width;this.canvas.height=height;}if(this.overlay.width!==overlayWidth||this.overlay.height!==overlayHeight){this.overlay.width=overlayWidth;this.overlay.height=overlayHeight;}return changed;}
    cameraState(deltaTime){const c=this.camera,alpha=this.drag?1:1-Math.exp(-18*Math.min(Math.max(deltaTime||1/60,0),.1));c.target=c.target.map((value,index)=>lerp(value,c.desiredTarget[index],alpha));c.radius=lerp(c.radius,c.desiredRadius,alpha);c.azimuth=lerp(c.azimuth,c.desiredAzimuth,alpha);c.elevation=lerp(c.elevation,c.desiredElevation,alpha);const basis=this.cameraBasis(c.azimuth,c.elevation),near=Math.max(.001,this.bounds.radius*.002),far=Math.max(100,this.bounds.radius*40),projection=this.options.projection==='orthographic'?orthographic(c.radius*.62,this.canvas.width/this.canvas.height,near,far):perspective(Math.PI/4,this.canvas.width/this.canvas.height,near,far),mvp=multiply(projection,basis.matrix),motion=Math.abs(c.radius-c.desiredRadius)+Math.abs(c.azimuth-c.desiredAzimuth)+Math.abs(c.elevation-c.desiredElevation)+c.target.reduce((sum,value,index)=>sum+Math.abs(value-c.desiredTarget[index]),0)>.00001;return {...basis,mvp,motion};}
    useSurface(mvp,color,geometry){const gl=this.gl,p=this.surfaceProgram,source=geometry||this.surface;gl.useProgram(p);gl.uniformMatrix4fv(gl.getUniformLocation(p,'uMvp'),false,new Float32Array(mvp));gl.uniform4fv(gl.getUniformLocation(p,'uColor'),color);const keyLight=gl.getUniformLocation(p,'uKeyLight'),fillLight=gl.getUniformLocation(p,'uFillLight');if(keyLight)gl.uniform3fv(keyLight,new Float32Array([-.45,-.65,1]));if(fillLight)gl.uniform3fv(fillLight,new Float32Array([.65,.35,.45]));gl.bindBuffer(gl.ARRAY_BUFFER,source.position.buffer);const pos=gl.getAttribLocation(p,'aPosition');if(pos>=0){gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,0,0);}const normal=gl.getAttribLocation(p,'aNormal');if(normal>=0&&source.normal){gl.bindBuffer(gl.ARRAY_BUFFER,source.normal.buffer);gl.enableVertexAttribArray(normal);gl.vertexAttribPointer(normal,3,gl.FLOAT,false,0,0);}if(source.index)gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,source.index);}
    drawLine(buffer,mvp,color,mode,size){const gl=this.gl;if(!buffer)return;const p=this.lineProgram;gl.useProgram(p);gl.uniformMatrix4fv(gl.getUniformLocation(p,'uMvp'),false,new Float32Array(mvp));gl.uniform4fv(gl.getUniformLocation(p,'uColor'),color);gl.uniform1f(gl.getUniformLocation(p,'uSize'),size||1);gl.uniform1f(gl.getUniformLocation(p,'uRound'),mode===gl.POINTS?1:0);gl.lineWidth(Math.min(4,size||1));gl.bindBuffer(gl.ARRAY_BUFFER,buffer.buffer);const pos=gl.getAttribLocation(p,'aPosition');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,0,0);gl.drawArrays(mode,0,buffer.count);this.currentDrawCalls++;}
    sampledLine(line,density,familiesByKind){if(line.selected)return true;if(density<=0)return false;const families=familiesByKind.get(line.kind)||[],family=line.family||line.kind+'-'+line.order;if(families.length<=2)return true;const count=Math.max(1,Math.min(families.length,Math.round(families.length*clamp(density,.01,1))));for(let i=0;i<count;i++)if(families[Math.round(i*(families.length-1)/(count-1))]===family)return true;return false;}
    refreshVisibleLines(){const familiesByKind=new Map();this.lines.forEach(line=>{if(line.kind==='debugMesh')return;const family=line.family||line.kind+'-'+line.order,items=familiesByKind.get(line.kind)||[];if(!items.includes(family))items.push(family);familiesByKind.set(line.kind,items);});const complete=['wire','debug'].includes(this.options.mode),stationDensity=complete?1:this.options.stationDensity,waterDensity=complete?1:this.options.waterlineDensity,longitudinalDensity=complete?1:this.options.longitudinalDensity;this.visibleLineBuffers=this.lines.filter(line=>{if(line.kind==='debugMesh')return false;if(line.kind==='keel')return this.options.showKeel;if(line.kind==='chine')return this.options.showChine;if(line.kind==='sheer')return this.options.showSheer;if(line.kind==='section'||line.kind==='sectionBottom')return this.options.showStations&&this.sampledLine(line,stationDensity,familiesByKind);if(line.kind==='waterline')return this.options.showWaterlines&&this.sampledLine(line,waterDensity,familiesByKind);if(line.kind==='draft')return this.options.showWaterlines;if(line.kind==='longitudinal')return this.options.showLongitudinals&&this.sampledLine(line,longitudinalDensity,familiesByKind);return false;});this.debugLineBuffers=this.lines.filter(line=>line.kind==='debugMesh');this.performance.visibleCurveSets=this.visibleLineBuffers.length;this.performance.visibleCurveVertices=this.visibleLineBuffers.reduce((sum,line)=>sum+(line.buffer?.count||0),0);this.debug.visibleCurveSets=this.performance.visibleCurveSets;this.debug.visibleCurveVertices=this.performance.visibleCurveVertices;}
    visibleCurves(){return this.visibleLineBuffers;}
    recordPerformance(started,motion){const now=performance.now(),gap=now-(this.performance.lastRenderedAt||0);if(gap>250){this.performance.windowStarted=now;this.performance.windowFrames=0;this.performance.windowRenderMs=0;}const wasIdle=this.performance.idle,elapsed=now-this.performance.windowStarted;this.performance.lastRenderedAt=now;this.performance.frames++;this.performance.windowFrames++;this.performance.lastRenderMs=now-started;this.performance.windowRenderMs+=this.performance.lastRenderMs;this.performance.drawCalls=this.currentDrawCalls;this.performance.idle=!motion&&!this.drag;let publish=this.performance.frames===1||wasIdle!==this.performance.idle;if(elapsed>=250){this.performance.fps=this.performance.windowFrames*1000/elapsed;this.performance.averageRenderMs=this.performance.windowRenderMs/Math.max(1,this.performance.windowFrames);this.performance.windowStarted=now;this.performance.windowFrames=0;this.performance.windowRenderMs=0;publish=true;}this.debug.performance={...this.performance};if(publish)this.callbacks.onPerformance?.(this.debug.performance);}
    render(timestamp){
      const started=performance.now(),delta=this.lastFrameTime?(timestamp-this.lastFrameTime)/1000:1/60;this.lastFrameTime=timestamp;const gl=this.gl,state=this.cameraState(delta),xray=this.options.mode==='xray',surfaceVisible=!['curves','wire'].includes(this.options.mode);this.currentDrawCalls=0;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(.018,.055,.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);
      if(surfaceVisible&&this.surface.position&&this.surface.normal){if(xray){gl.enable(gl.BLEND);gl.depthMask(false);}else gl.disable(gl.BLEND);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);this.useSurface(state.mvp,[.07,.46,.86,xray ? .36 : 1]);gl.drawArrays(gl.TRIANGLES,0,this.surface.count);this.currentDrawCalls++;this.debug.surfaceDraw={count:this.surface.count,indexed:false,error:gl.getError()};gl.disable(gl.POLYGON_OFFSET_FILL);gl.depthMask(true);}
      gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);if(this.options.showGrid)this.drawLine(this.gridBuffer,state.mvp,[.28,.52,.7,.13],gl.LINES,.6);if(this.options.showAxes){gl.disable(gl.DEPTH_TEST);this.axisVectors.forEach(axis=>{this.drawLine(axis.shaft,state.mvp,axis.color,gl.LINES,1.3);this.drawLine(axis.head,state.mvp,axis.color,gl.TRIANGLES,1);});gl.enable(gl.DEPTH_TEST);}
      if(this.options.showWaterplane&&this.planeBuffer&&this.planeNormal){this.useSurface(state.mvp,[.22,.72,1,xray ? .14 : .07],{position:this.planeBuffer,normal:this.planeNormal});gl.depthMask(false);gl.drawArrays(gl.TRIANGLES,0,this.planeBuffer.count);this.currentDrawCalls++;gl.depthMask(true);}
      if(this.options.mode!=='surface')this.visibleLineBuffers.forEach(line=>this.drawLine(line.buffer,state.mvp,line.color,gl.LINE_STRIP,line.width||1));if(this.options.mode==='debug')this.debugLineBuffers.forEach(line=>this.drawLine(line.buffer,state.mvp,line.color,gl.LINES,line.width||1));if((this.options.showOffsets||this.options.mode==='debug')&&this.pointBuffer)this.drawLine(this.pointBuffer,state.mvp,[.45,.80,1,1],gl.POINTS,7*Math.min(window.devicePixelRatio||1,1.5));
      this.drawGizmo(state);this.lastState=state;this.debug.lastGlError=gl.getError();this.debug.phase='rendered';this.recordPerformance(started,state.motion);window.__hydroViewerDebug=this.debug;if(state.motion&&!this.drag)this.requestRender();
    }
    drawGizmo(state){const ctx=this.overlayContext,width=this.overlay.width,height=this.overlay.height,cssWidth=Math.max(1,this.overlay.clientWidth||135),cssHeight=Math.max(1,this.overlay.clientHeight||112),ratio=width/cssWidth,designWidth=150,designHeight=126,scaleToFit=Math.min(cssWidth/designWidth,cssHeight/designHeight),offsetX=(cssWidth-designWidth*scaleToFit)/2,offsetY=(cssHeight-designHeight*scaleToFit)/2;ctx.clearRect(0,0,width,height);ctx.save();ctx.scale(ratio,ratio);ctx.translate(offsetX,offsetY);ctx.scale(scaleToFit,scaleToFit);ctx.fillStyle='rgba(4,17,30,.68)';ctx.strokeStyle='rgba(126,180,221,.18)';ctx.lineWidth=1;ctx.beginPath();if(typeof ctx.roundRect==='function')ctx.roundRect(3,3,144,120,8);else ctx.rect(3,3,144,120);ctx.fill();ctx.stroke();const origin=[43,42],axes=[{v:[1,0,0],color:'#ff5c7a',name:'X'},{v:[0,1,0],color:'#55c7ff',name:'Y'},{v:[0,0,1],color:'#45e3a3',name:'Z'}],arrow=(dx,dy,color,name)=>{const len=Math.hypot(dx,dy);if(len<.001)return;const ux=dx/len,uy=dy/len,tip=[origin[0]+dx,origin[1]+dy],base=[tip[0]-ux*6,tip[1]-uy*6],side=[-uy*2.9,ux*2.9];ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.65;ctx.beginPath();ctx.moveTo(...origin);ctx.lineTo(...base);ctx.stroke();ctx.beginPath();ctx.moveTo(...tip);ctx.lineTo(base[0]+side[0],base[1]+side[1]);ctx.lineTo(base[0]-side[0],base[1]-side[1]);ctx.closePath();ctx.fill();ctx.font='700 10px ui-monospace,Consolas';ctx.fillText(name,tip[0]+ux*6-3,tip[1]+uy*6+3);};axes.forEach(axis=>arrow(dot(axis.v,state.right)*26,-dot(axis.v,state.up)*26,axis.color,axis.name));ctx.fillStyle='#d9edff';ctx.beginPath();ctx.arc(...origin,2.4,0,Math.PI*2);ctx.fill();ctx.font='9px ui-monospace,Consolas';const legend=(y,color,left,right)=>{ctx.fillStyle=color;ctx.fillText(left,9,y);ctx.fillText(right,75,y);};legend(78,'#ff5c7a','+X PROA','−X POPA');legend(92,'#55c7ff','+Y BE','−Y BB');legend(106,'#45e3a3','+Z TOPO','−Z FUNDO');ctx.restore();}
    candidateAt(event){if(!this.lastState)return null;const rect=this.canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*(this.canvas.width/rect.width),y=(event.clientY-rect.top)*(this.canvas.height/rect.height);let best=null;for(const item of this.pickPoints){const p=project(item.position,this.lastState.mvp,this.canvas.width,this.canvas.height);if(!p)continue;const distance=Math.hypot(p.x-x,p.y-y);if(!best||distance<best.distance||(Math.abs(distance-best.distance)<.001&&item.type==='original'))best={...item,distance};}return best&&best.distance<18*(window.devicePixelRatio||1)?best:null;}
    updateHover(event){const candidate=this.candidateAt(event);const changed=(!candidate&&!this.hover)||(candidate&&(!this.hover||candidate.position!==this.hover.position));this.hover=candidate;if(changed)this.callbacks.onHover?.(candidate);}
    pick(event){if(this.drag)return;const candidate=this.candidateAt(event);if(!candidate)return;this.callbacks.onPick?.(candidate);}
    requestRender(){if(this.framePending)return;this.framePending=true;this.frame=requestAnimationFrame(timestamp=>{this.framePending=false;try{this.render(timestamp);}catch(error){this.debug.phase='error';this.debug.error=error.message;window.__hydroViewerDebug=this.debug;this.errorLabel.textContent='Falha na renderização 3D: '+error.message;this.errorLabel.style.display='block';}});}
    getPerformanceStats(){return {...this.performance,vertices:this.debug.surfaceVertices||0,triangles:this.debug.surfaceTriangles||0,visibleCurveSets:this.debug.visibleCurveSets||0,visibleCurveVertices:this.debug.visibleCurveVertices||0};}
    destroy(){if(this.framePending)cancelAnimationFrame(this.frame);this.resizeObserver?.disconnect();window.removeEventListener('resize',this.handleWindowResize);this.clearData();this.overlay.remove();this.errorLabel.remove();}
  }

  window.HydroRender3D={create:(canvas,callbacks)=>new HydroRender3D(canvas,callbacks)};
})();
